baseurl: http://gavinln.github.io/blog-site/
languageCode: en-us
title: Human Learning Machine Learning
metadataformat: "yaml"

pygmentsstyle: "default"

theme: "hyde"

params:
    themeColor: "theme-base-0b"
...
