baseurl: http://gavinln.github.io/blog-site/
languageCode: en-us
title: Human Learning Machine Learning
metadataformat: "yaml"
canonifyurls: true

pygmentsstyle: "default"

theme: "hyde"

params:
    themeColor: "theme-base-0b"

site:
    params:
        description: "A human learning machine learning"
...
