---
- name: upgrade system and packages
  apt: upgrade=dist

- name: Install unzip
  apt: name=unzip state=installed

- name: install python dev
  apt: name=python-dev state=installed

- name: Install ffmpeg
  apt: name=ffmpeg state=installed

- name: Install Pip
  apt: name=python-pip state=installed

- name: install httpie
  pip: name=httpie state=present

- name: install tmuxp
  pip: name=tmuxp state=present
