---
- name: install gitric
  pip: name=gitric state=present

- name: install pip3
  apt: name=python3-pip state=installed

- name: update pip3 to the latest version
  pip: name=pip state=latest

- name: install httpie
  pip: name=httpie state=present

- name: install tmuxp
  pip: name=tmuxp state=present
